# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00efc8986edfee6946c6cb49b6925be329685cacd65fbb733113897cb7ae27290038087e9505294a6c3e0c1df0667fce53c748ab1e5fd0721b7b215e512c3209

test:
  secret_key_base: abd02976b84aadc74a215d70e34d5bc15e24143225ab99aa92c93afcf321132718134ad4743ceb8093ce9d6758ae590bd8315da65a2c03b5650e3fe635b562b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
